name: CI
on:
  push: 
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando o código
        uses: actions/checkout@v2
      - name: Configurando nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Instalando as dependências
        run: npm install
      - name: Testando a aplicação
        run: npm test
        env:
          CI: true