name: CI
on:
  push: 
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install